// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhyqjyztkvgfyzhafetn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoeXFqeXp0a3ZnZnl6aGFmZXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5OTM5NTgsImV4cCI6MjA3ODU2OTk1OH0.obQX9BtFlik9tWc99p5IN5hmXqIXCTnMBYTAH6yQ14Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});